### ISSUE TITLE
add puma to gemfile

### ISSUE THREAD

**Issue by damir** [CBIIT/nci-match-patient-api#3]

**Comment by raseel-mohamed** [comment]
Curious, though... puma is used for Rack applications, how are we planning to use it for this rails app. Or are we switching to Rack

**Comment by damir** [comment]
Any rails app is a rack compliant app. Many other ruby web frameworks uses rack in front.

There is a config.ru file in rails root which will boot the app using any rack compliant web server - https://github.com/CBIIT/nci-match-patient-api/blob/master/config.ru.

You can read more here - http://guides.rubyonrails.org/rails_on_rack.html.

I am doing this because puma is faster than default webrick webserver and is also multi threaded which can be useful.

**Comment by raseel-mohamed** [comment]
Thanks for the information. learn something everyday

**Comment by damir** [comment]
Because nci-match-ui client fetches data in parallel from the patient server we can speed up dashboard load time for few seconds using puma in threaded mode. 

With webrick server all requests are queued and the last response will wait for all previous response to finish - total response time is the sum of all individual responses.

With puma I got difference from 8-9 seconds to 5-6 seconds on my local setup.

Some routes are very slow mainly because there is no pagination on server. After we fix this, the response times should go below 100ms.

To use puma first install the puma gem with bundler and then paste this into puma.rb file and put it into config folder:

```
threads 8,32
workers 3
preload_app!
```

Then start the server as usual with rails s command.

**Comment by damir** [comment]
Shan added entry to the gemfile.
